package main

import (
	"google.golang.org/protobuf/compiler/protogen"
)

func main() {
	protogen.Options{}.Run(func(gen *protogen.Plugin) error {
		for _, protoFile := range gen.Files {
			if protoFile.Generate {
				filename := protoFile.GeneratedFilenamePrefix + "_counter.pb.go"
				g := gen.NewGeneratedFile(filename, protoFile.GoImportPath)

				g.P("// Code generated by protoc-gen-counter. DO NOT EDIT.")
				g.P("")
				g.P("package ", protoFile.GoPackageName)
				g.P("")

				for _, m := range protoFile.Messages {
					for _, f := range m.Fields {
						if f.Desc.IsList() {
							g.P("func (x *", m.GoIdent, ")", "Count() int {")
							g.P(`return len(x.`, f.GoName, `)`)
							g.P("}")
							g.P("")
						}
					}
				}
			}
		}
		return nil
	})
}
